In [1]:
#Creating DataSet by this (Manually by your own choice)
import pandas as pd
cf = pd.DataFrame(
    {
        "Name" : [ " yashmeen " , " Nihal " , " N/A " ] ,
        "age"  : [ 18, 19, 0 ] ,
        "address" : ["Kurali" , "Sunder Nagar", " N/A " ]
    }
)

In [7]:
cf #used to see whole dataset

         Name  age       address
0   yashmeen    18        Kurali
1      Nihal    19  Sunder Nagar
2        N/A     0          N/A

In [51]:
cf["age"] #we can watch any single column by self by this, its details-datatype-etc.

0    18
1    19
2     0
Name: age, dtype: int64

In [63]:
#Series means column
#Making any Series from Scratch

marks = pd.Series([45,67,99] , name="Marks")

In [65]:
cf["Percentage"] = pd.Series([45.6,64.4,0])
cf

         Name  age       address  Marks  Percentage
0   yashmeen    18        Kurali     45        45.6
1      Nihal    19  Sunder Nagar     67        64.4
2        N/A     0          N/A      99         0.0

In [70]:
#Maximum value
cf["Percentage"].max()

64.4

In [71]:
#Minimum Value
cf["Percentage"].min()

0.0

In [73]:
#Series min/max value
marks.min()

45

In [75]:
#Describing Dataset, Describes about count mean  std min etc.
cf.describe()

             age      Marks  Percentage
count   3.000000   3.000000    3.000000
mean   12.333333  70.333333   36.666667
std    10.692677  27.153882   33.116361
min     0.000000  45.000000    0.000000
25%     9.000000  56.000000   22.800000
50%    18.000000  67.000000   45.600000
75%    18.500000  83.000000   55.000000
max    19.000000  99.000000   64.400000

In [12]:
#Making Series 
series = [12,34,45,454]
dx = pd.Series(series)
dx

0     12
1     34
2     45
3    454
dtype: int64

In [15]:
dy = pd.Series(series , index=["data1","data2","data3","data4"])
dy

data1     12
data2     34
data3     45
data4    454
dtype: int64

In [23]:
data = [["Nihal", 19,2006], ["Yashmeen", 19,2007], ["noob", 87,1957]]
df1 = pd.DataFrame(data, columns=["Name", "Age", "Year"], index=[1,2,3])
df1

       Name  Age  Year
1     Nihal   19  2006
2  Yashmeen   19  2007
3      noob   87  1957

In [27]:
data2 = {
    "Fruits" : ['Apple', 'Mango', 'Banana', ' Strawberry'],
    "Price" : [15,47,7,19],
    "season" : ["Winter", "Summer", "all", "N/A"]
}
df3= pd.DataFrame(data2)
df3

        Fruits  Price  season
0        Apple     15  Winter
1        Mango     47  Summer
2       Banana      7     all
3   Strawberry     19     N/A

In [29]:
df4= pd.Series(data2)
df4

Fruits    [Apple, Mango, Banana,  Strawberry]
Price                         [15, 47, 7, 19]
season             [Winter, Summer, all, N/A]
dtype: object

In [31]:
#loc = Labled based Selection
#in slicing if i will say 1 to 3 it'll given 1 to 3 , it only happenes in loc only
df3

        Fruits  Price  season
0        Apple     15  Winter
1        Mango     47  Summer
2       Banana      7     all
3   Strawberry     19     N/A

In [33]:
df3.loc[1]

Fruits     Mango
Price         47
season    Summer
Name: 1, dtype: object

In [37]:
df3.loc[1:3]

        Fruits  Price  season
1        Mango     47  Summer
2       Banana      7     all
3   Strawberry     19     N/A

In [42]:
df3["Fruits" ]

0          Apple
1          Mango
2         Banana
3     Strawberry
Name: Fruits, dtype: object

In [44]:
df3.loc[1:3,"Fruits":"Price"] #Slicing

        Fruits  Price
1        Mango     47
2       Banana      7
3   Strawberry     19

In [46]:
#iloc = index based selection
#The indexing and slicing are same as the all except loc
df3.iloc[1:4]

        Fruits  Price  season
1        Mango     47  Summer
2       Banana      7     all
3   Strawberry     19     N/A

In [49]:
df3.iloc[1:4, 0:2] #Only works on index not on label data (Important)

        Fruits  Price
1        Mango     47
2       Banana      7
3   Strawberry     19

In [ ]:
#loc = access data rows and colummns in label
#iloc = access data rows and columns in index