In [1]:
#Handson - concept of pandas and python|

In [2]:
#create a list tuple set with the value of 1 to 10
list1 = [1,2,3,4,5,6,7,8,9,10]
tuple1 = (1,2,3,4,5,6,7,8,9,10)
set1 = {1,2,3,4,5,6,7,8,9,10}
#create each datatype into pandas series
import pandas as pd
Pd_Series_list = pd.Series(list1)
Pd_Series_list

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [3]:
Pd_Series_tuple = pd.Series(tuple1)
Pd_Series_tuple

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [4]:
set2 = pd.Series(set1)

TypeError: 'set' type is unordered

In [5]:
#set will give you error cause it is unordered already.

In [6]:
#Create a sample series with 10 numbers.
#print the first five nmbers
#print the last five numbers
#update the fifth index to 200
#Delete the first element
sample = pd.Series((1,2,3,4,5,6,7,8,9,10))
sample

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [7]:
sample.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
sample.iloc[0:5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
sample.tail()

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [10]:
sample[5]=200
sample

0      1
1      2
2      3
3      4
4      5
5    200
6      7
7      8
8      9
9     10
dtype: int64

In [11]:
sample

0      1
1      2
2      3
3      4
4      5
5    200
6      7
7      8
8      9
9     10
dtype: int64

In [12]:
#Create a disct with values in list and create it to dataframe
dic = {
    'Name' : ['Yashmeen', 'Nihal', 'N/A'],
    'Age' : [19, 20, 0],
    'Adress' : ['abc' , 'def' , 'ijk']
}
dic_to_dataframe = pd.DataFrame(dic)
dic_to_dataframe

       Name  Age Adress
0  Yashmeen   19    abc
1     Nihal   20    def
2       N/A    0    ijk

In [13]:
#Rename Name to Student Name
dic_to_dataframe.rename(columns={"Name":"Student Name"}, inplace =True)
dic_to_dataframe

  Student Name  Age Adress
0     Yashmeen   19    abc
1        Nihal   20    def
2          N/A    0    ijk

In [14]:
#All column where age is greater than and equal to 19
age_greater = dic_to_dataframe[dic_to_dataframe['Age']>=19]
age_greater

  Student Name  Age Adress
0     Yashmeen   19    abc
1        Nihal   20    def

In [24]:
#load dataset and print it "adult_data-TA Bhuvan.csv"

In [27]:
df = pd.read_csv('adult_data-TA Bhuvan.csv')
df

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...
995,56,Private,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,55,United-States,>50K
996,45,Private,Masters,Divorced,Prof-specialty,Not-in-family,White,Male,45,United-States,<=50K
997,48,Federal-gov,Bachelors,Divorced,Exec-managerial,Unmarried,White,Male,58,United-States,>50K
998,40,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,<=50K
999,39,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K

In [29]:
#head, tail, info and describe ( and also describe for all), sample atleast 6
df.head()

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K

In [31]:
df.tail()

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
995,56,Private,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,55,United-States,>50K
996,45,Private,Masters,Divorced,Prof-specialty,Not-in-family,White,Male,45,United-States,<=50K
997,48,Federal-gov,Bachelors,Divorced,Exec-managerial,Unmarried,White,Male,58,United-States,>50K
998,40,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,<=50K
999,39,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K

In [33]:
df.sample(6)

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
944,20,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,<=50K
721,41,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,60,United-States,<=50K
396,45,Private,Some-college,Divorced,Handlers-cleaners,Unmarried,White,Female,40,United-States,<=50K
145,31,Private,HS-grad,Never-married,Transport-moving,Unmarried,Black,Female,30,United-States,<=50K
107,30,Private,11th,Never-married,Handlers-cleaners,Own-child,White,Male,40,United-States,<=50K
185,34,Private,HS-grad,Married-civ-spouse,Adm-clerical,Husband,Black,Male,40,United-States,<=50K

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             1000 non-null   int64
 1   workclass       938 non-null    object
 2   education       1000 non-null   object
 3   marital-status  1000 non-null   object
 4   occupation      938 non-null    object
 5   relationship    1000 non-null   object
 6   race            1000 non-null   object
 7   sex             1000 non-null   object
 8   hours-per-week  1000 non-null   int64
 9   native-country  982 non-null    object
 10  income          1000 non-null   object
dtypes: int64(2), object(9)
memory usage: 86.1+ KB

In [35]:
df.describe()

              age  hours-per-week
count  1000.00000     1000.000000
mean     38.05100       39.876000
std      13.34948       12.018114
min      17.00000        1.000000
25%      28.00000       40.000000
50%      36.00000       40.000000
75%      46.00000       45.000000
max      90.00000       99.000000

In [37]:
df.describe(include='all')

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
count,1000.00000,938,1000,1000,938,1000,1000,1000,1000.000000,982,1000
unique,NaN,6,16,7,14,6,5,2,NaN,28,2
top,NaN,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,NaN,United-States,<=50K
freq,NaN,698,321,443,126,376,847,671,NaN,902,768
mean,38.05100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.876000,NaN,NaN
std,13.34948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.018114,NaN,NaN
min,17.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,28.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
50%,36.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
75%,46.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,NaN,NaN
max,90.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.000000,NaN,NaN

In [39]:
#check for the null and duplicate if there then drop both
df.isnull()

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False

In [40]:
df.isnull().sum()

age                0
workclass         62
education          0
marital-status     0
occupation        62
relationship       0
race               0
sex                0
hours-per-week     0
native-country    18
income             0
dtype: int64

In [43]:
df.dropna(inplace=True)
df.isnull().sum()

age               0
workclass         0
education         0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [45]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 922, dtype: bool

In [46]:
df.duplicated().sum()

9

In [54]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

0

In [55]:
#finding total rows and columns ( rows, columns )
df.shape

(913, 11)