In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("openpowerlifting.csv")
df

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

In [3]:
df.iloc[0:5]

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47

In [4]:
df.head()

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47

In [5]:
df.tail()

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.5,347.5,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.5,322.5,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.5,367.5,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.0,320.0,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.5,362.5,2,205.18

In [6]:
df.sample()

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
175356,5760,Allan Edelmon,M,Single-ply,NaN,Boys,122.47,125,NaN,215.46,NaN,133.81,NaN,204.12,553.38,1,316.7

In [7]:
df.sample(8)

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
213335,6172,David McCoy,M,Single-ply,NaN,Boys,124.74,125,NaN,226.80,NaN,129.27,NaN,201.85,557.92,2,318.06
150566,5177,Jaclyn McClellan,F,Wraps,NaN,Amateur Open,108.41,110,NaN,167.83,NaN,68.04,NaN,174.63,410.50,1,334.82
1330,23,Jeff Ray,M,Raw,NaN,Open,110.00,110,NaN,NaN,NaN,NaN,NaN,275.00,275.00,1,161.84
330,5,Janet Martin,F,Raw,48.0,M-2,108.86,90+,NaN,NaN,NaN,60.00,NaN,NaN,60.00,1,48.89
104234,3528,Bjarne Havnen,M,Single-ply,NaN,Master 40-49,118.25,120,NaN,NaN,NaN,210.00,NaN,NaN,210.00,1,121.16
155697,5284,Leon McLean,M,Raw,NaN,Masters 70-74,98.25,100,NaN,NaN,NaN,145.15,NaN,NaN,145.15,1,88.98
326449,7655,Kenny Carlisle,M,Raw,47.0,Master Men 45-49,116.39,125,NaN,175.00,NaN,-160.00,NaN,NaN,NaN,DQ,NaN
157617,5353,Mark Scott,M,Wraps,28.0,Open,141.61,140+,NaN,292.57,NaN,199.58,NaN,278.96,771.11,1,430.17

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386414 entries, 0 to 386413
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   MeetID          386414 non-null  int64
 1   Name            386414 non-null  object
 2   Sex             386414 non-null  object
 3   Equipment       386414 non-null  object
 4   Age             147147 non-null  float64
 5   Division        370571 non-null  object
 6   BodyweightKg    384012 non-null  float64
 7   WeightClassKg   382602 non-null  object
 8   Squat4Kg        1243 non-null    float64
 9   BestSquatKg     298071 non-null  float64
 10  Bench4Kg        1962 non-null    float64
 11  BestBenchKg     356364 non-null  float64
 12  Deadlift4Kg     2800 non-null    float64
 13  BestDeadliftKg  317847 non-null  float64
 14  TotalKg         363237 non-null  float64
 15  Place           385322 non-null  object
 16  Wilks           362194 non-null  float64
dtypes: float64(10), int64(1), object(6)
memory usage: 50.1+ MB

In [9]:
#Will describe my data in satistical way!
#it wont give object datatype - cause it works with maths and statistic only
#we have to include it byself
df.describe()

,MeetID,Age,BodyweightKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Wilks
count,386414.000000,147147.000000,384012.000000,1243.000000,298071.000000,1962.000000,356364.000000,2800.000000,317847.000000,363237.000000,362194.000000
mean,5143.015804,31.668237,86.934912,107.036404,176.569941,45.722905,118.347509,113.597193,195.040633,424.000249,301.080601
std,2552.099838,12.900342,23.140843,166.976620,69.222785,151.668221,54.848850,170.201657,61.580675,196.355147,116.360396
min,0.000000,5.000000,15.880000,-440.500000,-477.500000,-360.000000,-522.500000,-461.000000,-410.000000,11.000000,13.730000
25%,2979.000000,22.000000,70.300000,87.500000,127.500000,-90.000000,79.380000,110.000000,147.500000,272.160000,237.380000
50%,5960.000000,28.000000,83.200000,145.000000,174.630000,90.250000,115.000000,157.500000,195.000000,424.110000,319.660000
75%,7175.000000,39.000000,100.000000,212.500000,217.720000,167.500000,150.000000,219.990000,238.140000,565.000000,379.290000
max,8481.000000,95.000000,242.400000,450.000000,573.790000,378.750000,488.500000,418.000000,460.400000,1365.310000,779.380000

In [10]:
df.describe(include="object")

                  Name     Sex Equipment Division WeightClassKg   Place
count           386414  386414    386414   370571        382602  385322
unique          136687       2         5     4246            51      81
top     Sverre Paulsen       M       Raw     Open            90       1
freq               183  299045    186317    68618         35981  194693

In [11]:
df.describe(include="all")

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
count,386414.000000,386414,386414,386414,147147.000000,370571,384012.000000,382602,1243.000000,298071.000000,1962.000000,356364.000000,2800.000000,317847.000000,363237.000000,385322,362194.000000
unique,NaN,136687,2,5,NaN,4246,NaN,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81,NaN
top,NaN,Sverre Paulsen,M,Raw,NaN,Open,NaN,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
freq,NaN,183,299045,186317,NaN,68618,NaN,35981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,194693,NaN
mean,5143.015804,NaN,NaN,NaN,31.668237,NaN,86.934912,NaN,107.036404,176.569941,45.722905,118.347509,113.597193,195.040633,424.000249,NaN,301.080601
std,2552.099838,NaN,NaN,NaN,12.900342,NaN,23.140843,NaN,166.976620,69.222785,151.668221,54.848850,170.201657,61.580675,196.355147,NaN,116.360396
min,0.000000,NaN,NaN,NaN,5.000000,NaN,15.880000,NaN,-440.500000,-477.500000,-360.000000,-522.500000,-461.000000,-410.000000,11.000000,NaN,13.730000
25%,2979.000000,NaN,NaN,NaN,22.000000,NaN,70.300000,NaN,87.500000,127.500000,-90.000000,79.380000,110.000000,147.500000,272.160000,NaN,237.380000
50%,5960.000000,NaN,NaN,NaN,28.000000,NaN,83.200000,NaN,145.000000,174.630000,90.250000,115.000000,157.500000,195.000000,424.110000,NaN,319.660000
75%,7175.000000,NaN,NaN,NaN,39.000000,NaN,100.000000,NaN,212.500000,217.720000,167.500000,150.000000,219.990000,238.140000,565.000000,NaN,379.290000
max,8481.000000,NaN,NaN,NaN,95.000000,NaN,242.400000,NaN,450.000000,573.790000,378.750000,488.500000,418.000000,460.400000,1365.310000,NaN,779.380000

In [12]:
df.describe(exclude="float")

,MeetID,Name,Sex,Equipment,Division,WeightClassKg,Place
count,386414.000000,386414,386414,386414,370571,382602,385322
unique,NaN,136687,2,5,4246,51,81
top,NaN,Sverre Paulsen,M,Raw,Open,90,1
freq,NaN,183,299045,186317,68618,35981,194693
mean,5143.015804,NaN,NaN,NaN,NaN,NaN,NaN
std,2552.099838,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,2979.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,5960.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,7175.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,8481.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#Changing the name of column
df.rename(columns={"MeetID":"Id"})

,Id,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

In [14]:
df
#it again got MeetID from ID , means it simply make things copy type not actual change the column name

,MeetID,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

In [15]:
df.rename(columns={"MeetID":"Id"}, inplace= True)
df
#we will use inplace=True so that it'll be permanent fix!!

,Id,Name,Sex,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

In [18]:
df.rename(columns={'Sex':'Gender'}, inplace=True)
df

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

In [20]:
#Null Values
#Empty values called null values (NaN)
df.isnull() #give me null data

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,False,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,True,True,True,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,True,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,False,False,False,False,True,False,False,False,True,True,True,True,True,False,False,False,False
386410,False,False,False,False,True,False,False,False,True,True,True,True,True,False,False,False,False
386411,False,False,False,False,True,False,False,False,True,True,True,True,True,False,False,False,False
386412,False,False,False,False,True,False,False,False,True,True,True,True,True,False,False,False,False
386413,False,False,False,False,True,False,False,False,True,True,True,True,True,False,False,False,False

In [22]:
df.isnull().sum() #sum it up every none valus and give me data

Id                     0
Name                   0
Gender                 0
Equipment              0
Age               239267
Division           15843
BodyweightKg        2402
WeightClassKg       3812
Squat4Kg          385171
BestSquatKg        88343
Bench4Kg          384452
BestBenchKg        30050
Deadlift4Kg       383614
BestDeadliftKg     68567
TotalKg            23177
Place               1092
Wilks              24220
dtype: int64

In [23]:
#if we have null values in dataset we can't go forward with it, it'll give us issues if we want to go in machine learning and all
#Lets deal with null values
# 1. Dropping null values = Removing the null values a
# we cant delete if the dataset is small and precious
# 2. Fill the null values with some values
#Specifically if each and every value is important or dataset is small

In [26]:
df_copy = df.copy()
#made copy of dataframe in df_copy
df_copy

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,NaN,NaN,NaN,95.25,NaN,NaN,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,NaN,NaN,NaN,31.75,NaN,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,NaN,Elite,113.58,125,NaN,NaN,NaN,NaN,NaN,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,NaN,Elite,119.02,125,NaN,NaN,NaN,NaN,NaN,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,NaN,Elite,120.29,125,NaN,NaN,NaN,NaN,NaN,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,NaN,Elite,126.73,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,NaN,Elite,129.46,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18

In [29]:
df_copy.isnull().sum()

Id                     0
Name                   0
Gender                 0
Equipment              0
Age               239267
Division           15843
BodyweightKg        2402
WeightClassKg       3812
Squat4Kg          385171
BestSquatKg        88343
Bench4Kg          384452
BestBenchKg        30050
Deadlift4Kg       383614
BestDeadliftKg     68567
TotalKg            23177
Place               1092
Wilks              24220
dtype: int64

In [32]:
df_copy.dropna(inplace=True)

In [34]:
df_copy.isnull().sum()
#Dropped all the null values

Id                0
Name              0
Gender            0
Equipment         0
Age               0
Division          0
BodyweightKg      0
WeightClassKg     0
Squat4Kg          0
BestSquatKg       0
Bench4Kg          0
BestBenchKg       0
Deadlift4Kg       0
BestDeadliftKg    0
TotalKg           0
Place             0
Wilks             0
dtype: int64

In [35]:
#fill the null values
# 1.fill with a value
# 2. fill with mean, median, mode

In [51]:
df.fillna(0, inplace=True)
df.isnull().sum()

Id                0
Name              0
Gender            0
Equipment         0
Age               0
Division          0
BodyweightKg      0
WeightClassKg     0
Squat4Kg          0
BestSquatKg       0
Bench4Kg          0
BestBenchKg       0
Deadlift4Kg       0
BestDeadliftKg    0
TotalKg           0
Place             0
Wilks             0
dtype: int64

In [56]:
#Filling with mean
df.fillna(df['Bench4Kg'].mean())
#it will fill with all nan value to bench4kg average

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,0.0,47.63,0.0,20.41,0.0,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,0.0,142.88,0.0,95.25,0.0,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,0.0,142.88,0.0,95.25,0.0,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,0.0,0.00,0.0,95.25,0.0,0.00,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,0.0,0.00,0.0,31.75,0.0,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,0.0,Elite,113.58,125,0.0,0.00,0.0,0.00,0.0,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,0.0,Elite,119.02,125,0.0,0.00,0.0,0.00,0.0,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,0.0,Elite,120.29,125,0.0,0.00,0.0,0.00,0.0,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,0.0,Elite,126.73,140,0.0,0.00,0.0,0.00,0.0,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,0.0,Elite,129.46,140,0.0,0.00,0.0,0.00,0.0,362.50,362.50,2,205.18

In [59]:
#individual mean value filling
df['BodyweightKg']= df['BodyweightKg'].fillna(df['BodyweightKg'].mean())

In [61]:
#Duplicate value (means if rows are duplicated "all are same to each other , body wright , age and name etc.")
#we have to drop dulicates everytime
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
386409    False
386410    False
386411    False
386412    False
386413    False
Length: 386414, dtype: bool

In [65]:
df.duplicated().sum()

545

In [69]:
#we have to drop them 
df.drop_duplicates(inplace=True)
df.duplicated().sum()
#dropped

0

In [71]:
#Filter the data
df

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,0.0,47.63,0.0,20.41,0.0,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,0.0,142.88,0.0,95.25,0.0,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,0.0,142.88,0.0,95.25,0.0,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,0.0,0.00,0.0,95.25,0.0,0.00,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,0.0,0.00,0.0,31.75,0.0,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386409,8481,William Barabas,M,Multi-ply,0.0,Elite,113.58,125,0.0,0.00,0.0,0.00,0.0,347.50,347.50,2,202.60
386410,8481,Justin Zottl,M,Multi-ply,0.0,Elite,119.02,125,0.0,0.00,0.0,0.00,0.0,322.50,322.50,3,185.77
386411,8481,Jake Anderson,M,Multi-ply,0.0,Elite,120.29,125,0.0,0.00,0.0,0.00,0.0,367.50,367.50,1,211.17
386412,8481,Jeff Bumanglag,M,Multi-ply,0.0,Elite,126.73,140,0.0,0.00,0.0,0.00,0.0,320.00,320.00,3,181.85
386413,8481,Shane Hammock,M,Multi-ply,0.0,Elite,129.46,140,0.0,0.00,0.0,0.00,0.0,362.50,362.50,2,205.18

In [77]:
#give me all values where the gender is female only
female = df[df['Gender']=='F']
female

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
0,0,Angie Belk Terry,F,Wraps,47.0,Mst 45-49,59.60,60,0.0,47.63,0.0,20.41,0.0,70.31,138.35,1,155.05
1,0,Dawn Bogart,F,Single-ply,42.0,Mst 40-44,58.51,60,0.0,142.88,0.0,95.25,0.0,163.29,401.42,1,456.38
2,0,Dawn Bogart,F,Single-ply,42.0,Open Senior,58.51,60,0.0,142.88,0.0,95.25,0.0,163.29,401.42,1,456.38
3,0,Dawn Bogart,F,Raw,42.0,Open Senior,58.51,60,0.0,0.00,0.0,95.25,0.0,0.00,95.25,1,108.29
4,0,Destiny Dula,F,Raw,18.0,Teen 18-19,63.68,67.5,0.0,0.00,0.0,31.75,0.0,90.72,122.47,1,130.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386396,8481,Diane Gmiter,F,Multi-ply,0.0,Elite,81.56,82.5,0.0,0.00,0.0,0.00,0.0,235.00,235.00,1,212.77
386397,8481,Sheri Whetham,F,Multi-ply,0.0,Elite,83.91,90,0.0,0.00,0.0,0.00,0.0,205.00,205.00,2,182.90
386398,8481,Molly Headly,F,Multi-ply,0.0,Elite,86.73,90,0.0,0.00,0.0,0.00,0.0,220.00,220.00,1,193.20
386399,8481,Jessica Bowersock,F,Multi-ply,0.0,Elite,111.22,90+,0.0,0.00,0.0,0.00,0.0,205.00,205.00,2,166.30
386401,8481,Samantha Coleman,F,Multi-ply,0.0,Elite,156.58,90+,0.0,0.00,0.0,0.00,0.0,250.00,250.00,1,192.09

In [79]:
female.shape

(87247, 17)

In [81]:
df.shape

(385869, 17)

In [88]:
#Two conditions!
df[(df['Age']>45) & (df['BodyweightKg']>90)]
#we have to use & and | for and and or

,Id,Name,Gender,Equipment,Age,Division,BodyweightKg,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
46,0,Danny Plyler,M,Raw,59.0,Mst 55-59,99.70,100,195.04,188.24,0.0,176.90,0.0,219.99,585.13,1,356.53
52,0,Raymond Hubbe,M,Raw,66.0,Mst 65-69,98.34,100,0.00,0.00,0.0,149.69,0.0,0.00,149.69,1,91.72
56,0,Al Reiss,M,Wraps,61.0,Mst 60-64,101.79,110,176.90,170.10,0.0,104.33,0.0,167.83,442.26,1,267.30
57,0,Rob Bumgarner,M,Multi-ply,58.0,Mst 55-59,105.96,110,0.00,0.00,0.0,158.76,0.0,0.00,158.76,1,94.57
58,0,Rob Bumgarner,M,Multi-ply,58.0,Open Senior,105.96,110,0.00,0.00,0.0,158.76,0.0,0.00,158.76,1,94.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385394,8464,Alistair Fairley,M,Raw,51.0,0,98.09,100,0.00,205.00,0.0,150.00,0.0,220.00,575.00,1,352.71
385396,8464,Terry Taylor,M,Wraps,52.0,0,98.65,100,0.00,210.00,0.0,155.00,0.0,235.00,600.00,3,367.18
385949,8477,Alex Podshiabiakin,M,Multi-ply,50.0,Heavy,153.59,0,0.00,0.00,0.0,263.08,0.0,0.00,263.08,7,145.08
385953,8477,Tom Waldrep,M,Multi-ply,51.0,Heavy,99.34,0,0.00,0.00,0.0,362.87,0.0,0.00,362.87,4,221.43
385954,8477,Greg Powell,M,Multi-ply,49.0,Heavy,99.79,0,0.00,0.00,0.0,362.87,0.0,0.00,362.87,5,221.02